name: Sync with Databricks
on:
  push:
    branches:
      - 'feature/**'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.2

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests

      - name: Install Requests
        run: pip install requests
  

      - name: Run Python script
        
        env:
          bearer_token: ${{secrets.BEARER_TOKEN}}
        run: python ./db_reposync_py_cd.py ${{secrets.BEARER_TOKEN}}
