name: Sync with Databricks
on:
  push:
    branches:
      - 'feature/**'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests

      - name: Install Requests
        run: pip install requests
  
      - name: Execute Python script # Run the run.py to get the latest data
        run: |
            echo "DATABRICKS_API_TOKEN=${{ secrets.DATABRICKS_TOKEN_DEV }}">> $GITHUB_ENV
            env:
              DATABRICKS_API_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV}}
              python ./db_reposync_py_cd.py
